// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // .env defines DIRECT_URL (non-pooled, for migrations); fall back to the
    // pooled DATABASE_URL so the CLI still works when only that is set.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
