import {describe,it,expect,vi} from 'vitest';
import {CatalogPager,catalogQuery,catalogScope,cardQuery} from '../../aranya-next/src/lib/catalog-pagination';
import type {CatalogPage} from '../../aranya-next/src/lib/types';
const page=(id:string,cursor:string|null=null):CatalogPage=>({items:[{productId:id,slug:id} as CatalogPage['items'][number]],featured:[],total:24,facets:{category:['Rare Estate'],form:[],origin:[],flavour:[]},nextCursor:cursor,hasNextPage:!!cursor,market:'INTERNATIONAL'});
const deferred=<T>()=>{let resolve!:(value:T)=>void;let reject!:(error:Error)=>void;const promise=new Promise<T>((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
describe('progressive catalog',()=>{
  it('canonicalizes shared query identity and forwards full-data filters',()=>{const q=catalogQuery({cat:'Rare Estate',flavour:'Warm,Floral,Warm',sort:'rating'});expect(q.flavour).toEqual(['Floral','Warm']);expect(cardQuery(q)).toMatchObject({limit:8,categoryName:'Rare Estate',sort:'rating'});expect(catalogScope(q,'local')).not.toBe(catalogScope(q,'intl'));});
  it('fetches only on demand and deduplicates a double Load more click',async()=>{const next=deferred<CatalogPage>(),load=vi.fn(()=>next.promise),pager=new CatalogPager(load,'intl:',page('a','next'));expect(load).not.toHaveBeenCalled();pager.loadMore();pager.loadMore();expect(load).toHaveBeenCalledTimes(1);next.resolve(page('b'));await vi.waitFor(()=>expect(pager.snapshot.loading).toBe(false));expect(pager.snapshot.page?.items.map(p=>p.productId)).toEqual(['a','b']);});
  it('aborts and ignores a former-query page even when its API completes late',async()=>{const old=deferred<CatalogPage>(),fresh=deferred<CatalogPage>(),signals:AbortSignal[]=[];const load=vi.fn((_scope:string,_cursor:string|undefined,signal:AbortSignal)=>{signals.push(signal);return signals.length===1?old.promise:fresh.promise;});const pager=new CatalogPager(load,'intl:',page('a','next'));pager.loadMore();pager.reset('intl:cat=Rare');expect(signals[0].aborted).toBe(true);fresh.resolve(page('rare'));await vi.waitFor(()=>expect(pager.snapshot.page?.items[0].productId).toBe('rare'));old.resolve(page('wrong'));await Promise.resolve();expect(pager.snapshot.page?.items.map(p=>p.productId)).toEqual(['rare']);});
  it('preserves current cards on failure and retries the same cursor',async()=>{const load=vi.fn().mockRejectedValueOnce(new Error('Unavailable')).mockResolvedValueOnce(page('b')),pager=new CatalogPager(load,'intl:',page('a','next'));pager.loadMore();await vi.waitFor(()=>expect(pager.snapshot.error).toBe('Unavailable'));expect(pager.snapshot.page?.items[0].productId).toBe('a');pager.retry();await vi.waitFor(()=>expect(pager.snapshot.loading).toBe(false));expect(load.mock.calls.map(c=>c[1])).toEqual(['next','next']);expect(pager.snapshot.page?.items).toHaveLength(2);});
  it('rejects a looping cursor and permits explicit retry',async()=>{const load=vi.fn().mockResolvedValue(page('b','next')),pager=new CatalogPager(load,'intl:',page('a','next'));pager.loadMore();await vi.waitFor(()=>expect(pager.snapshot.error).toContain('next catalog page'));expect(pager.snapshot.page?.items).toHaveLength(1);});
  it('market reset clears old currency rows immediately and ignores their late completion',async()=>{const next=deferred<CatalogPage>(),load=vi.fn(()=>next.promise),pager=new CatalogPager(load,'intl:',page('a','next'));pager.loadMore();pager.reset('local:',{...page('local'),market:'LOCAL'});next.resolve(page('usd'));await Promise.resolve();expect(pager.snapshot.page?.market).toBe('LOCAL');expect(pager.snapshot.page?.items[0].productId).toBe('local');});
});
